name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: ["main"]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: 2.9.4

      - name: Fix linting issues, fail if not possible
        run: deno lint --fix

      - name: Fix formatting issues
        run: deno fmt

      - name: Commit changes back to the branch
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
